### ISSUE TITLE
Define project colour palette and apply it to the main menu 

### ISSUE THREAD

**Issue by Danitim** [Dmitriy2442/CT_project#6]
# Changing colours 101

### Window background colour
1) Open `mainwindow.cpp` file
2) Fine 27th code line (it should look like this `this->setStyleSheet("background-color: #222222")`)
3) Change hex colour code to any other

### Text colour
1) Open one of the `.ui` files located in `ui/` folder (for example `mainmenu.ui`)
2) It should have opened in Qt Designer window
3) Find the text whose colour you want to change
4) Right click on it -> choose `Change StyleSheet...`
5) In the css-like file find the line which looks like `color: blue`
6) Change hex colour code to any other

### *It would be cool if you could find a way to save this palette for later use throughout the project*

**Comment by Dmitriy2442** [comment]
Visually appealing colors added
